import slugify from '../utils/slugify'
import {
  orderRankField,
  orderRankOrdering,
} from '@sanity/orderable-document-list';

export default {
  title: "Work",
  name: 'work',
  type: "document",
  fields: [
    orderRankField({ type: 'category', hidden: true }),
    {
      title: "Title",
      description: "The name of this piece of work",
      name: "title",
      type: "string",
      validation: Rule => Rule.required()
    },
    {
      title: "Year",
      name: "year",
      type: "string",
      validation: Rule => Rule.required()
    },
    
    {
      title: "Services",
      description: "The services delivered on this piece of work, eg: 'Art Direction, Visual Identity, etc...'",
      name: "services",
      type: 'array',
      of: [{type: 'string'}]
    },
    {
      title: "Main Image",
      description: "The image that will be displayed first on this piece of work",
      name: "teaserImage",
      type: "defaultImage",
      validation: Rule => Rule.required()
    },
    {
      title: 'Image Blocks',
      name: 'imageBlocks',
      description: 'The modular image blocks for this project',
      type: 'array',
      of: [
        {type: 'textBlock', title: 'Text Block'},
        {type: 'singleImageBlock', title: 'Single Image'},
        {type: 'doubleImageBlock', title: 'Double Image'}
      ],
    },
    {
      name: 'slug',
      type: 'slug',
      title: 'Slug',
      description: 'This is required for page routing and can be auto-generated by pressing "generate"',
      options: {
        source: (doc) => {
          let titleSlug = ''
          let campaignSlug = ''
          if (doc.title) {
            titleSlug = `${doc.title}`
          } else {
            titleSlug = ''
          }

          if (doc.campaignTitle) {
            campaignSlug = `-${doc.campaignTitle}`
          } else {
            campaignSlug = ''
          }

          return `${titleSlug}${campaignSlug}`;
        },
        maxLength: 96,
        slugify: (input) => slugify(`${input}`)
      },
      validation: Rule => Rule.required()
    },
    {
      title: 'SEO / Share Settings',
      name: 'seo',
      type: 'seo'
    }
  ],
  preview: {
    select: {
      title: 'title',
      subtitle: 'campaignTitle',
      media: 'teaserImage'
    }
  }
}